function render(){
 const d=diagnosis(),q=currentQuestion(),symptoms=symptomLabels(),proposals=proposalList(d.primary,d.secondary),plan=roadmap(d.primary),primaryRisk=riskLevel(d.primary.score);
 $('#welcome').innerHTML=`<div class="card hero"><span class="eyebrow">約5分｜経営者向け</span><h2>忙しさの正体を、<br>「仕事が詰まっている場所」から見つけます。</h2><p>「何のシステムを入れるか」ではなく、時間・売上・社長依存・顧客対応・数字管理・引き継ぎの6方向から、会社の見えにくい詰まりを診断します。</p><button class="btn primary" data-action="start">仕事詰まり診断をはじめる</button><small>正確な数字は不要です。普段の感覚に近いものを選んでください。</small></div>`;
 $('#symptoms').innerHTML=`<div class="card panel center-card"><div class="head"><div><h2 class="question">最近、こんなことは起きていませんか？</h2><p class="helper">「課題名」ではなく、実際に起きていることを選んでください。1つから進めます。最大8つまで選べます。</p></div><span class="counter">${state.selectedSymptoms.length} / 8件</span></div><div class="notice">社長自身が「問題ではない」と思っていることでも、時間や売上の詰まりにつながっている場合があります。少しでも当てはまれば選んでください。</div><div class="symptom-grid">${SYMPTOMS.map(s=>`<button class="symptom ${state.selectedSymptoms.includes(s.id)?'active':''}" data-symptom="${s.id}"><b>${state.selectedSymptoms.includes(s.id)?'✓ ':''}${s.label}</b><span>${s.desc}</span></button>`).join('')}</div><div class="navrow sticky-actions"><button class="btn" data-go="welcome">戻る</button><button class="btn primary ${state.selectedSymptoms.length?'':'disabled'}" data-action="symptom-next">会社の状態を確認する</button></div></div>`;
 $('#questions').innerHTML=`<div class="card panel center-card"><div class="stepper">${QUESTIONS.map((_,i)=>`<span class="step-chip ${i===state.questionIndex?'active':''}">${i+1}</span>`).join('')}</div><span class="tag blue">${state.questionIndex+1} / ${QUESTIONS.length}</span><h2 class="question" style="margin-top:14px">${q.text}</h2><p class="helper">正解はありません。今の状態に一番近いものを選んでください。</p><div class="question-scale">${q.options.map(([label,val,desc])=>`<button class="${state.answers[q.key]===val?'active':''}" data-answer="${q.key}" data-value="${val}"><span><b>${label}</b><small>${desc}</small></span><span>${state.answers[q.key]===val?'✓':''}</span></button>`).join('')}</div><div class="navrow"><button class="btn" data-action="question-back">戻る</button><button class="btn primary" data-action="question-next">${state.questionIndex===QUESTIONS.length-1?'診断結果を見る':'次へ'}</button></div></div>`;
 $('#thinking').innerHTML=`<div class="card thinking"><h2>会社の「仕事詰まり」を分析しています</h2><p class="helper">表面の困りごと、隠れた原因、経営への影響、最初の一歩を整理しています。</p><div class="dots"><span></span><span></span><span></span></div></div>`;
 const axesHtml=d.axes.map(a=>`<div class="card axis-card"><div class="axis-head"><h4>${a.label}</h4><strong>${a.score}</strong></div><div class="meter"><span style="width:${a.score}%"></span></div><p>${a.desc}</p></div>`).join('');
 const proposalHtml=proposals.map((p,i)=>`<div class="proposal-card"><h4>${i+1}. ${p}</h4><p>${i<2?'最初に小さく試しやすく、効果を確認しやすい改善です。':'必要性を確認しながら、次の段階で追加できます。'}</p><div class="why">診断根拠：${d.primary.label}${i>=4&&d.secondary?`＋${d.secondary.label}`:''}の点数が高いため</div></div>`).join('');
 $('#result').innerHTML=`<div class="card result-hero"><span class="label">小さな会社の仕事詰まり診断</span><h2>あなたの会社は<br>「${d.type.name}」の傾向があります。</h2><p>${d.type.summary}</p></div><div class="summary-strip section-gap"><div class="card"><span>選んだ現象</span><strong>${symptoms.length}件</strong></div><div class="card"><span>最も強い詰まり</span><strong>${d.primary.short}</strong></div><div class="card"><span>詰まり度</span><strong>${d.primary.score}/100</strong></div><div class="card"><span>診断の確信度</span><strong>${d.confidence}</strong></div></div><div class="card diagnosis-core section-gap"><span class="tag blue">診断の核心</span><h3>${d.type.hidden}</h3><p>${d.type.summary} 表面的には「${symptoms.slice(0,3).join('・')||'日々の忙しさ'}」が気になっていますが、根本では「${d.type.hidden}」が複数の問題を同時に起こしている可能性があります。</p></div><div class="layer-grid section-gap"><div class="card layer surface"><h4>表面に見えている悩み</h4><p>${symptoms.slice(0,5).join('／')||'忙しさや確認作業の増加'}</p></div><div class="card layer cause"><h4>隠れた原因</h4><p>${d.type.hidden}。さらに、次点は「${d.secondary.label}」です。</p></div><div class="card layer impact"><h4>経営への影響</h4><p>${d.type.impact}につながりやすい状態です。</p></div></div><div class="card panel section-gap"><div class="head"><div><h3>6方向の診断結果</h3><p class="sub">点数が高いほど、優先的に確認したい領域です。</p></div><span class="score-badge ${primaryRisk[1]}">${d.primary.label}：${primaryRisk[0]}</span></div><div class="axis-grid">${axesHtml}</div></div><div class="card panel section-gap"><div class="head"><div><h3>回答内容から、こんな状態にできます</h3><p class="sub">機能名ではなく、仕事がどう変わるかで提案しています。</p></div><span class="tag green">具体的な改善案</span></div><div class="proposal-grid">${proposalHtml}</div><div class="notice good">すべてを一度に導入する必要はありません。最初の1〜2個だけ試し、実際に時間・返信速度・確認回数が改善したかを見てから広げます。</div></div><div class="card panel section-gap"><div class="head"><div><h3>7日・30日・90日の改善ロードマップ</h3><p class="sub">社長の負担を増やさず、小さく始める順番です。</p></div></div><div class="roadmap"><div class="roadmap-item day7"><b>最初の7日</b><h4>現状を見える化</h4><p>${plan[0]}</p></div><div class="roadmap-item day30"><b>30日後</b><h4>1つの仕事を仕組み化</h4><p>${plan[1]}</p></div><div class="roadmap-item day90"><b>90日後</b><h4>効果を確認して広げる</h4><p>${plan[2]}</p></div></div></div><div class="card panel no-need section-gap"><h3>今は、やらなくてよいこと</h3><p>${noNeed(d.primary)}</p></div><div class="card panel section-gap"><div class="head"><div><h3>この診断になった根拠</h3><p class="sub">回答から重要なものだけ抜き出しています。</p></div></div><div class="evidence-list">${symptoms.slice(0,4).map(s=>`<div class="evidence-item"><span class="dot"></span><p>${s}</p></div>`).join('')}<div class="evidence-item"><span class="dot"></span><p>${QUESTIONS.find(x=>x.key==='owner_absence').options[state.answers.owner_absence||0][0]}</p></div><div class="evidence-item"><span class="dot"></span><p>${QUESTIONS.find(x=>x.key==='money_view').options[state.answers.money_view||0][0]}</p></div></div></div><div class="navrow"><button class="btn" data-go="symptoms">回答を見直す</button><button class="btn primary" data-go="future">改善後の目的を選ぶ</button></div>`;
 $('#future').innerHTML=`<div class="card panel center-card"><span class="tag green">改善の方向性を調整</span><h2 class="question" style="margin-top:14px">改善できたら、何を一番増やしたいですか？</h2><p class="helper">ここを選ぶと、相談時の提案順がより具体的になります。</p><div class="future-grid">${['売上につながる時間','現場に集中する時間','社長の自由な時間','社員が自分で動ける状態'].map(x=>`<button class="future ${state.future===x?'active':''}" data-future="${x}">${x}</button>`).join('')}</div><div class="navrow"><button class="btn" data-go="result">戻る</button><button class="btn primary ${state.future?'':'disabled'}" data-go="contact">次へ</button></div></div>`;
 $('#contact').innerHTML=`<div class="card cta center-card"><span class="tag blue">相談前に売り込みはしません</span><h3 style="margin-top:14px">実際の書類や画面を1つ見ながら、<br>最初にやることを絞りませんか？</h3><p>診断結果をそのまま売るのではなく、今あるやり方・社員数・件数を確認し、「やること」と「今はやらないこと」を整理します。</p><div class="cta-buttons">${contactBtn('無料で改善順を相談する',state.contact.form,'primary')}${contactBtn('LINEで診断結果を相談する',state.contact.line,'green')}${contactBtn('サービスを見る',state.contact.website)}</div><p style="margin-top:18px"><b>${esc(state.contact.business)}</b><br>${esc(state.contact.area)}</p>${MODE==='face'?'<div style="margin-top:12px"><button class="btn" data-go="sales">営業メモへ</button> <button class="btn" data-go="report">診断書を見る</button></div>':''}</div>`;
 renderFace(d,proposals,plan,symptoms);
 $('#progressBar').style.width=progress()+'%';$('#progressText').textContent=progress()+'%';bind();
}
