function renderFace(d,proposals,plan,symptoms){
 if(MODE!=='face'){ $('#sales').innerHTML='';$('#settings').innerHTML='';$('#report').innerHTML='';return }
 const script=`【診断の核心】\n${d.type.summary}\n\n【表面の悩み】\n${symptoms.slice(0,5).join('、')}\n\n【隠れた原因】\n${d.type.hidden}\n\n【最初に提案すること】\n1. ${proposals[0]}\n2. ${proposals[1]}\n\n【今は勧めないこと】\n${noNeed(d.primary)}\n\n【次に確認すること】\n実際の書類・画面を1つ見て、月の件数、担当者、例外対応、開始希望時期を確認します。`;
 $('#sales').innerHTML=`<div class="grid c2"><div class="card panel admin"><div class="head"><div><h3>営業担当メモ</h3><p class="sub">顧客には見せない内部情報です。</p></div></div><div class="admin-grid"><div class="field"><label>決裁者</label><select id="decision">${['不明','本人・代表者','他の決裁者あり'].map(x=>`<option ${state.sales.decision===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>予算感</label><select id="budget">${['未確認','まず無料・低予算で試したい','10〜30万円','30万円以上'].map(x=>`<option ${state.sales.budget===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>温度感</label><select id="temperature">${['低','中','高'].map(x=>`<option ${state.sales.temperature===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>会社名・屋号</label><input id="companyName" value="${esc(state.company)}"></div><div class="field full"><label>面談メモ</label><textarea id="salesMemo">${esc(state.sales.memo)}</textarea></div></div></div><div class="card panel"><div class="head"><div><h3>診断に基づく提案トーク</h3><p class="sub">売り込みではなく、気づきを伝える順番です。</p></div><button class="btn" id="copyScript">コピー</button></div><div class="script" id="scriptText">${esc(script)}</div></div></div>`;
 $('#settings').innerHTML=`<div class="card panel admin"><h3>連絡先・リンク設定</h3><p class="sub">この設定だけは次回の診断にも引き継がれます。</p><div class="admin-grid">${[['business','屋号・会社名'],['person','担当者名'],['website','ホームページURL'],['line','LINE URL'],['email','メールアドレス'],['phone','電話番号'],['form','無料相談フォームURL'],['area','対応地域']].map(([k,l])=>`<div class="field"><label>${l}</label><input data-contact="${k}" value="${esc(state.contact[k])}"></div>`).join('')}</div><div class="navrow"><button class="btn" data-go="sales">戻る</button><button class="btn primary" id="saveSettings">設定を保存</button></div></div>`;
 $('#report').innerHTML=`<div class="report"><div class="cover"><span>小さな会社の仕事詰まり診断</span><h2>${esc(state.company||'御社')}の隠れた課題と改善ロードマップ</h2><p>${new Date().toLocaleDateString('ja-JP')}｜${esc(state.contact.business)}</p></div><div class="rsec"><h3>1．診断結果</h3><p><b>${d.type.name}</b></p><p>${esc(d.type.summary)}</p></div><div class="rsec"><h3>2．表面の悩み・隠れた原因・経営への影響</h3><table><tr><th>表面の悩み</th><th>隠れた原因</th><th>経営への影響</th></tr><tr><td>${esc(symptoms.slice(0,5).join('、'))}</td><td>${esc(d.type.hidden)}</td><td>${esc(d.type.impact)}</td></tr></table></div><div class="rsec"><h3>3．6方向の診断</h3><table><tr><th>領域</th><th>点数</th></tr>${d.axes.map(a=>`<tr><td>${esc(a.label)}</td><td>${a.score}/100</td></tr>`).join('')}</table></div><div class="rsec"><h3>4．回答内容から実現できること</h3><ol>${proposals.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></div><div class="rsec"><h3>5．7日・30日・90日</h3><p><b>7日：</b>${esc(plan[0])}</p><p><b>30日：</b>${esc(plan[1])}</p><p><b>90日：</b>${esc(plan[2])}</p></div><div class="rsec"><h3>6．今はやらなくてよいこと</h3><p>${esc(noNeed(d.primary))}</p></div><div class="rsec"><h3>7．相談先</h3><p><b>${esc(state.contact.business)}</b><br>${esc(state.contact.person)}<br>${esc(state.contact.email)} ${state.contact.phone?'/ '+esc(state.contact.phone):''}<br>${esc(state.contact.area)}</p></div><button class="btn primary no-print" onclick="window.print()">PDF保存・印刷</button></div>`;
}
function bind(){
 $$('[data-view]').forEach(el=>el.onclick=()=>show(el.dataset.view));$$('[data-go]').forEach(el=>el.onclick=()=>show(el.dataset.go));
 const start=$('[data-action="start"]');if(start)start.onclick=()=>show('symptoms');
 $$('[data-symptom]').forEach(el=>el.onclick=()=>toggleSymptom(el.dataset.symptom));
 const next=$('[data-action="symptom-next"]');if(next)next.onclick=()=>{if(!state.selectedSymptoms.length){toast('1つ以上選んでください');return}state.questionIndex=0;save();render();show('questions')};
 $$('[data-answer]').forEach(el=>el.onclick=()=>selectAnswer(el.dataset.answer,el.dataset.value));
 const qn=$('[data-action="question-next"]');if(qn)qn.onclick=nextQuestion;const qb=$('[data-action="question-back"]');if(qb)qb.onclick=prevQuestion;
 $$('[data-future]').forEach(el=>el.onclick=()=>{const y=window.scrollY;state.future=el.dataset.future;save();render();show('future',{scroll:false});window.scrollTo(0,y)});
 const decision=$('#decision');if(decision)decision.onchange=()=>{state.sales.decision=decision.value;save()};const budget=$('#budget');if(budget)budget.onchange=()=>{state.sales.budget=budget.value;save()};const temperature=$('#temperature');if(temperature)temperature.onchange=()=>{state.sales.temperature=temperature.value;save()};const company=$('#companyName');if(company)company.onchange=()=>{state.company=company.value;save()};const memo=$('#salesMemo');if(memo)memo.onchange=()=>{state.sales.memo=memo.value;save()};
 const saveBtn=$('#saveSettings');if(saveBtn)saveBtn.onclick=()=>{$$('[data-contact]').forEach(el=>state.contact[el.dataset.contact]=el.value);saveSettings();toast('設定を保存しました');render();show('settings',{scroll:false})};
 const copyBtn=$('#copyScript'),script=$('#scriptText');if(copyBtn&&script)copyBtn.onclick=async()=>{try{await navigator.clipboard.writeText(script.textContent);toast('コピーしました')}catch{toast('コピーできませんでした')}};
 $('#restartBtn').onclick=()=>{if(confirm('診断内容を最初からやり直しますか？')){resetDiagnosis();render();show('welcome');toast('新しい診断を開始しました')}};
}
render();show(state.screen&&allowed(state.screen)?state.screen:'welcome',{scroll:false});
