function render(){
 const rank=rankResults(); const top=rank[0]; const conf=confidence(rank);
 const futureOptions=['営業','現場','休み','家族','趣味'];
 $('#welcome').innerHTML=`<div class="card hero"><span class="eyebrow">約3分で完了</span><h2>仕事で「めんどくさい」と感じることを、診断らしく整理します。</h2><p>最初に1つへ決めつけず、候補を比べながら優先順位を出します。結果は「最優先」「次にやること」「今は後回しでよいこと」まで分かります。</p><button class="btn primary" data-action="start">診断をはじめる</button><small>結果を見るだけでも大丈夫です。営業電話が自動でかかることはありません。</small></div>`;
 $('#pain').innerHTML=`<div class="card panel center-card"><div class="head"><div><h2 class="question">日々の仕事で、時間を取られているものを最大3つ選んでください</h2><p class="helper">1つだけでも進めます。最初に選んだものをそのまま結論にせず、あとで比べて優先順位を出します。</p></div><span class="tag blue">${state.selectedPains.length} / 3件選択</span></div><div class="option-grid">${PAINS.map(x=>`<button class="option ${state.selectedPains.includes(x[0])?'active':''}" data-pain="${x[0]}"><b>${state.selectedPains.includes(x[0])?'✓ ':''}${x[1]}</b><span>${x[2]}</span></button>`).join('')}</div><div class="navrow"><button class="btn" data-go="welcome">戻る</button><button class="btn primary ${state.selectedPains.length?'':'disabled'}" data-action="pain-next">次へ</button></div></div>`;
 const cq=currentQuestion();
 $('#question').innerHTML=`<div class="card panel center-card"><div class="stepper">${[...Array(totalQuestions())].map((_,i)=>`<span class="step-chip ${i===state.questionIndex?'active':''}">${i+1}</span>`).join('')}</div><span class="tag blue">${state.questionIndex+1} / ${totalQuestions()}</span><h2 class="question" style="margin-top:14px">${cq.text}</h2><p class="helper">${cq.type==='compare'?'選んだ候補を比べて、最優先を見極めます。':'全体の負担感を確認します。'}</p><div class="single-options">${cq.options.map(o=>{const active=cq.type==='compare'?state.compare[cq.key]===o.value:state.general[cq.key]===o.value;return `<button class="${active?'active':''}" data-answer="${cq.key}" data-answer-type="${cq.type}" data-value="${o.value}"><b>${o.label}</b>${o.desc?`<div class="muted" style="font-size:8px;margin-top:4px">${o.desc}</div>`:''}</button>`}).join('')}</div><div class="navrow"><button class="btn" data-action="question-back">戻る</button><button class="btn primary" data-action="question-next">${state.questionIndex===totalQuestions()-1?'診断する':'次へ'}</button></div></div>`;
 $('#thinking').innerHTML=`<div class="card thinking"><h2>回答をもとに考えています</h2><p class="helper">比較結果から、最優先と次点を整理しています。</p><div class="dots"><span></span><span></span><span></span></div></div>`;
 $('#result').innerHTML=`${top?`<div class="card result-hero"><span class="label">診断結果</span><h2>最優先で改善する仕事は<br>「${top.name}」です。</h2><p>「${top.reasons.join('、')}」という回答傾向から、今いちばん先に整えるべき仕事だと判断しました。</p></div>`:`<div class="card result-hero"><h2>まずは診断を進めてください</h2></div>`}<div class="grid c4" style="margin-top:13px"><div class="card kpi"><span>候補に挙げた課題</span><strong>${state.selectedPains.length}件</strong><small>最大3件</small></div><div class="card kpi"><span>現在使っている時間</span><strong>月約${monthlyHours()}時間</strong><small>概算</small></div><div class="card kpi"><span>減らせる可能性</span><strong>月約${possibleSavedHours()}時間</strong><small>無理のない目安</small></div><div class="card kpi"><span>診断の確信度</span><strong>${conf}</strong><small>差が小さい場合は要確認</small></div></div><div class="grid c2" style="margin-top:13px"><div class="card panel"><div class="head"><div><h3>優先順位</h3><p class="sub">最優先・次点・後回しで整理しました。</p></div></div>${rank.length?rank.map((r,i)=>`<div class="rank-item"><div class="rank-top"><div><h4>${i===0?'最優先':i===1?'次に改善':'今は後回し'}｜${r.name}</h4><span class="tag ${i===0?'green':i===1?'blue':'amber'}">${r.category}</span></div><span class="score-pill">${r.score}点</span></div><p>${r.reasons.length?r.reasons.join('、')+'。':''}${i===0?'売上・顧客への影響と負担の両方が大きいため、最優先です。':i===1?'重要ですが、まずは最優先の課題から着手する方が効果的です。':'改善余地はありますが、今すぐ最初に着手する優先度は相対的に低めです。'}</p></div>`).join(''):'<p class="muted">まだ診断が完了していません。</p>'}</div><div class="card panel recommend">${top?`<span class="tag green">あなたへのおすすめ</span><h3 style="margin-top:10px">${SERVICES[top.id].name}</h3><p>${SERVICES[top.id].desc}</p><div class="price">${Math.round(SERVICES[top.id].price/10000)}万円〜</div><p>まずは小さく始めて、効果が出るか確認しながら広げる方針がおすすめです。</p>`:'<p>診断後に表示されます。</p>'}</div></div><div class="grid c2" style="margin-top:13px"><div class="card panel"><div class="head"><div><h3>最初の一歩</h3><p class="sub">いきなり大きく変えず、順番に進めます。</p></div></div>${top?`<div class="rank-item"><h4>無料でできること</h4><p>${firstStepFor(top.id).free}</p></div><div class="rank-item"><h4>自社でできること</h4><p>${firstStepFor(top.id).self}</p></div><div class="rank-item"><h4>支援でできること</h4><p>${firstStepFor(top.id).support}</p></div>`:'<p class="muted">診断後に表示されます。</p>'}</div><div class="card panel"><div class="head"><div><h3>補足</h3><p class="sub">診断を断定しすぎないための説明です。</p></div></div><ul class="bullets"><li>最初に選んだものをそのまま結論にしているわけではありません。</li><li>「時間」「後回し」「影響」「繰り返し」を比べて優先順位を出しています。</li><li>上位の差が小さい場合は、実際の作業画面を確認すると順位が変わることがあります。</li></ul></div></div><div class="navrow"><button class="btn" data-go="pain">候補を選び直す</button><button class="btn primary" data-go="future">次へ</button></div>`;
 $('#future').innerHTML=`<div class="card panel center-card"><span class="tag green">年間約${possibleSavedHours()*12}時間</span><h2 class="question" style="margin-top:14px">空いた時間ができたら、何に使いたいですか？</h2><p class="helper">ここを選ぶと、提案の話し方や診断書の見せ方が自然になります。</p><div class="future-grid">${futureOptions.map(x=>`<button class="future ${state.future===x?'active':''}" data-future="${x}">${x}</button>`).join('')}</div><div class="navrow"><button class="btn" data-go="result">戻る</button><button class="btn primary ${state.future?'':'disabled'}" data-go="contact">次へ</button></div></div>`;
 $('#contact').innerHTML=`<div class="card cta center-card"><span class="tag blue">結果を見るだけでも大丈夫です</span><h3 style="margin-top:14px">この診断内容を、実際の業務に当てはめて確認しませんか？</h3><p>実際に使っている書類や画面を1つ見ながら、無理なく始められる改善の順番を整理します。強引な営業は行いません。</p><div class="cta-buttons">${contactBtn('無料相談を申し込む',state.contact.form,'primary')}${contactBtn('LINEで相談する',state.contact.line,'green')}${contactBtn('ホームページを見る',state.contact.website,'')}</div><p style="margin-top:18px"><b>${esc(state.contact.business)}</b><br>${esc(state.contact.area)}</p>${MODE==='face'?'<div style="margin-top:10px"><button class="btn" data-go="sales">営業メモへ</button> <button class="btn" data-go="report">診断書を見る</button></div>':''}</div>`;
 $('#sales').innerHTML=MODE==='face'?`<div class="grid c2"><div class="card panel admin"><div class="head"><div><h3>営業担当メモ</h3><p class="sub">顧客には見せない内部情報</p></div></div><div class="admin-grid"><div class="field"><label>決裁者</label><select id="decision"><option ${state.sales.decision==='不明'?'selected':''}>不明</option><option ${state.sales.decision==='本人・代表者'?'selected':''}>本人・代表者</option><option ${state.sales.decision==='他の決裁者あり'?'selected':''}>他の決裁者あり</option></select></div><div class="field"><label>予算感</label><select id="budget"><option ${state.sales.budget==='未確認'?'selected':''}>未確認</option><option ${state.sales.budget==='小さく試したい'?'selected':''}>小さく試したい</option><option ${state.sales.budget==='10〜30万円'?'selected':''}>10〜30万円</option><option ${state.sales.budget==='30万円以上'?'selected':''}>30万円以上</option></select></div><div class="field"><label>温度感</label><select id="temperature"><option ${state.sales.temperature==='低'?'selected':''}>低</option><option ${state.sales.temperature==='中'?'selected':''}>中</option><option ${state.sales.temperature==='高'?'selected':''}>高</option></select></div><div class="field"><label>会社名・屋号</label><input id="companyName" value="${esc(state.company)}"></div><div class="field" style="grid-column:1/-1"><label>面談メモ</label><textarea id="salesMemo">${esc(state.sales.memo)}</textarea></div></div></div><div class="card panel"><div class="head"><div><h3>提案トーク</h3><p class="sub">専門用語を抑えた説明用</p></div><button class="btn" id="copyScript">コピー</button></div><div class="script" id="scriptText">${top?esc(salesScript(top)):'診断後に表示されます。'}</div></div></div>`:'';
 $('#settings').innerHTML=MODE==='face'?`<div class="card panel admin"><div class="head"><div><h3>連絡先・リンク設定</h3><p class="sub">未定の項目は空欄のままで構いません。顧客画面では「準備中」と表示されます。</p></div></div><div class="admin-grid">${[['business','屋号・会社名'],['person','担当者名'],['website','ホームページURL'],['line','LINE URL'],['email','メールアドレス'],['phone','電話番号'],['form','無料相談フォームURL'],['area','対応地域']].map(([k,label])=>`<div class="field"><label>${label}</label><input data-contact="${k}" value="${esc(state.contact[k])}"></div>`).join('')}</div><div class="navrow"><button class="btn" data-go="sales">戻る</button><button class="btn primary" id="saveSettings">設定を保存</button></div></div>`:'';
 $('#report').innerHTML=MODE==='face'?`<div class="report"><div class="cover"><span>仕事ラクラク診断</span><h2>${esc(state.company||'御社')}の優先課題と最初の一歩</h2><p>${new Date().toLocaleDateString('ja-JP')}｜${esc(state.contact.business)}</p></div><div class="rsec"><h3>1．候補に挙がった課題</h3><p>${selectedPainObjects().map(x=>x[1]).join('、')||'未選択'}</p></div><div class="rsec"><h3>2．優先順位</h3><table><tr><th>順位</th><th>課題</th><th>点数</th><th>理由</th></tr>${rank.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td>${r.score}点</td><td>${esc(r.reasons.join('、'))}</td></tr>`).join('')}</table></div><div class="rsec"><h3>3．最優先で改善する仕事</h3><p><b>${top?esc(top.name):'未判定'}</b></p><p>${top?esc(SERVICES[top.id].desc):''}</p></div><div class="rsec"><h3>4．時間の改善余地</h3><table><tr><th>現在</th><th>削減できる可能性</th><th>年間</th></tr><tr><td>月約${monthlyHours()}時間</td><td>月約${possibleSavedHours()}時間</td><td>約${possibleSavedHours()*12}時間</td></tr></table></div><div class="rsec"><h3>5．最初の一歩</h3>${top?`<p><b>無料でできること：</b>${esc(firstStepFor(top.id).free)}</p><p><b>自社でできること：</b>${esc(firstStepFor(top.id).self)}</p><p><b>支援でできること：</b>${esc(firstStepFor(top.id).support)}</p>`:'<p>診断後に表示されます。</p>'}</div><div class="rsec"><h3>6．相談先</h3><p>${esc(state.contact.business)}／${esc(state.contact.person)}<br>${esc(state.contact.email)} ${state.contact.phone?'/ '+esc(state.contact.phone):''}<br>${esc(state.contact.area)}</p></div><button class="btn primary no-print" onclick="window.print()">PDF保存・印刷</button></div>`:'';
 $('#progressBar').style.width=progress()+'%';$('#progressText').textContent=progress()+'%';bind();
}
function bind(){
 $$('[data-view]').forEach(el=>el.onclick=()=>show(el.dataset.view));
 $$('[data-go]').forEach(el=>el.onclick=()=>show(el.dataset.go));
 const start=$('[data-action="start"]');if(start)start.onclick=()=>show('pain');
 $$('[data-pain]').forEach(el=>el.onclick=()=>togglePain(el.dataset.pain));
 const painNext=$('[data-action="pain-next"]');if(painNext)painNext.onclick=()=>{if(!state.selectedPains.length){toast('1つ以上選んでください');return}state.questionIndex=0;save();render();show('question')};
 $$('[data-answer]').forEach(el=>el.onclick=()=>setAnswer(el.dataset.answer,el.dataset.value,el.dataset.answerType));
 const qNext=$('[data-action="question-next"]');if(qNext)qNext.onclick=nextQuestion;
 const qBack=$('[data-action="question-back"]');if(qBack)qBack.onclick=prevQuestion;
 $$('[data-future]').forEach(el=>el.onclick=()=>{const y=window.scrollY;state.future=el.dataset.future;save();render();show('future',{scroll:false});window.scrollTo(0,y)});
 const decision=$('#decision');if(decision)decision.onchange=()=>{state.sales.decision=decision.value;save()};
 const budget=$('#budget');if(budget)budget.onchange=()=>{state.sales.budget=budget.value;save()};
 const temperature=$('#temperature');if(temperature)temperature.onchange=()=>{state.sales.temperature=temperature.value;save()};
 const companyName=$('#companyName');if(companyName)companyName.onchange=()=>{state.company=companyName.value;save()};
 const salesMemo=$('#salesMemo');if(salesMemo)salesMemo.onchange=()=>{state.sales.memo=salesMemo.value;save()};
 $$('[data-contact]').forEach(el=>el.onchange=()=>{state.contact[el.dataset.contact]=el.value});
 const saveSettings=$('#saveSettings');if(saveSettings)saveSettings.onclick=()=>{$$('[data-contact]').forEach(el=>state.contact[el.dataset.contact]=el.value);save();toast('設定を保存しました');render();show('settings',{scroll:false})};
 const copyScript=$('#copyScript'),scriptText=$('#scriptText');if(copyScript&&scriptText)copyScript.onclick=async()=>{try{await navigator.clipboard.writeText(scriptText.textContent);toast('コピーしました')}catch(e){toast('コピーできませんでした')}};
 $('#restartBtn').onclick=()=>{if(confirm('診断内容を最初からやり直しますか？')){const contact=clone(state.contact);const company=state.company;state=clone(DEFAULT);state.contact=contact;state.company=company;save();render();show('welcome');toast('診断内容をリセットしました')}};
}
render();show(state.screen&&allowed(state.screen)?state.screen:'welcome',{scroll:false});
