const PAINS=[
['invoice','請求書・領収書','請求や経費整理を後回しにしてしまう'],['estimate','見積書','案件ごとに作り直すのが面倒'],['reply','メール・LINE返信','営業時間外まで返信している'],['inquiry','問い合わせ対応','内容確認、返信、共有に時間がかかる'],['photos','写真整理','現場写真がスマホに散らばる'],['daily','日報・報告書','帰社後に思い出して書いている'],['documents','書類探し','必要な資料がすぐ見つからない'],['schedule','日程調整','候補日のやり取りが何往復もする'],['sns','SNS投稿','何を投稿するか毎回悩む'],['website','ホームページ','古い、問い合わせにつながらない'],['google','Googleマップ','情報や写真を放置している'],['busy','とにかく時間がない','代表者や一人の担当者に集中している']];
const SERVICES={invoice:['請求・経費作業の簡略化',70000,'入力・分類・保存方法をまとめ、請求や経費整理を簡単にします。'],estimate:['見積作成の仕組み化',80000,'過去案件や定型文を使い、見積書のたたき台を早く作れるようにします。'],reply:['返信文作成の仕組み化',50000,'よくある返信を整理し、メールやLINEの返信時間を短くします。'],inquiry:['問い合わせ対応の整理',150000,'問い合わせの要約、分類、返信案、担当共有をまとめます。'],photos:['現場写真の整理',80000,'案件ごとに写真をまとめ、探す時間を減らします。'],daily:['日報・報告書の簡略化',70000,'短いメモや音声から、日報のたたき台を作れるようにします。'],documents:['書類整理の仕組み化',50000,'フォルダ名や保存場所を統一し、誰でも探せる状態にします。'],schedule:['予約・日程調整の簡略化',50000,'候補日提示、予約、リマインドの手間を減らします。'],sns:['SNS投稿の仕組み化',50000,'投稿企画、文章、画像作成の流れを簡単にします。'],website:['問い合わせ導線の改善',100000,'強みや実績を整理し、問い合わせしやすいホームページやLPに改善します。'],google:['Googleビジネス改善',50000,'地域検索で見つけてもらうための情報や写真を整えます。'],busy:['仕事の棚卸しと省力化',50000,'時間を奪っている仕事を整理し、減らせる作業を一つずつ見つけます。']};
const DEFAULT={mode:'net',screen:'welcome',step:0,pain:'',answers:{amount:'週に数回',time:'30分〜1時間',person:'自分・代表者',repeat:'毎回ほぼ同じ'},future:'',sales:{decision:'不明',budget:'未確認',temperature:'中',memo:''},contact:{business:'デジタル御用聞き',person:'担当者未定',website:'',line:'',email:'',phone:'',form:'',area:'岡山県内を中心に対応'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],copy=v=>JSON.parse(JSON.stringify(v));
function load(){try{const x=JSON.parse(localStorage.getItem('workEasyV3')||'{}');return {...copy(DEFAULT),...x,answers:{...DEFAULT.answers,...(x.answers||{})},sales:{...DEFAULT.sales,...(x.sales||{})},contact:{...DEFAULT.contact,...(x.contact||{})}}}catch{return copy(DEFAULT)}}
let state=load();
function save(){localStorage.setItem('workEasyV3',JSON.stringify(state))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function pain(){return PAINS.find(x=>x[0]===state.pain)}
function service(){return SERVICES[state.pain]||['小さな業務改善',30000,'最も面倒な仕事を一つ選び、無理なく改善します。']}
function hours(){const n={'毎日':22,'週に数回':12,'週1回':4,'月に数回':3,'月1回':1}[state.answers.amount]||12,m={'10分未満':8,'10〜30分':20,'30分〜1時間':45,'1〜2時間':90,'2時間以上':150}[state.answers.time]||45;return Math.max(1,Math.round(n*m/60))}
function saved(){let r=state.answers.repeat==='毎回ほぼ同じ'?.65:state.answers.repeat==='半分くらい同じ'?.5:.35;if(state.answers.person==='自分・代表者')r+=.05;return Math.max(1,Math.round(hours()*Math.min(.75,r)))}
function annual(){return saved()*12}
function allowed(id){if(['welcome','pain','settings'].includes(id))return true;if(!state.pain)return false;if(id==='question')return true;if(['thinking','result','future','contact','sales','report'].includes(id))return state.step>=4;return true}
function show(id){if(!allowed(id)){toast('先に診断を進めてください');return}state.screen=id;save();$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const titles={welcome:['仕事を少しラクにする方法を探します','約3分。難しい専門用語は使いません。'],pain:['一番面倒な仕事を選んでください','今週いちばん気になったものを選ぶだけです。'],question:['もう少しだけ教えてください','質問は最大4つです。'],thinking:['診断しています','回答をもとに現実的な改善案を整理しています。'],result:['診断結果','最初に改善することを一つに絞りました。'],future:['空いた時間の使い道','改善後の未来を選んでください。'],contact:['無料相談','必要な方だけ、次の相談へ進めます。'],sales:['営業担当メモ','対面営業モード専用です。'],settings:['連絡先設定','リンクや連絡先は後から変更できます。'],report:['顧客向け診断書','PDFとして保存できます。']};$('#pageTitle').textContent=titles[id][0];$('#pageSub').textContent=titles[id][1];scrollTo({top:0,behavior:'smooth'})}
function render(){
 $('#welcome').innerHTML=`<div class="card hero"><span class="eyebrow">約3分で完了</span><h2>仕事で「めんどくさい」と感じることを、ひとつ減らしませんか？</h2><p>難しいシステムの話はしません。普段の仕事の中から、時間がかかっている作業を見つけ、無理なく減らす方法を考えます。</p><button class="btn primary" data-action="start">診断をはじめる</button><small>結果を見るだけでも大丈夫です。営業電話が自動でかかることはありません。</small></div>`;
 $('#pain').innerHTML=`<div class="card panel center-card"><div class="head"><div><h2 class="question">一番「なくなったらラク」と思う仕事はどれですか？</h2><p class="helper">迷った場合は、今週いちばん面倒だったものを選んでください。</p></div><span class="tag blue">1つだけ選択</span></div><div class="option-grid">${PAINS.map(x=>`<button class="option ${state.pain===x[0]?'active':''}" data-pain="${x[0]}"><b>${state.pain===x[0]?'✓ ':''}${x[1]}</b><span>${x[2]}</span></button>`).join('')}</div><div class="navrow"><button class="btn" data-go="welcome">戻る</button><button class="btn primary ${state.pain?'':'disabled'}" data-action="pain-next">次へ</button></div></div>`;
 const qs=[['amount',`「${pain()?.[1]||'その仕事'}」はどのくらい発生しますか？`,['毎日','週に数回','週1回','月に数回','月1回']],['time','1回あたり、どのくらい時間がかかりますか？',['10分未満','10〜30分','30分〜1時間','1〜2時間','2時間以上']],['person','主に誰がやっていますか？',['自分・代表者','事務担当','営業担当','複数人']],['repeat','毎回、作業内容は似ていますか？',['毎回ほぼ同じ','半分くらい同じ','毎回違う']]],q=qs[Math.min(state.step,3)];
 $('#question').innerHTML=`<div class="card panel center-card"><span class="tag blue">${Math.min(state.step+1,4)} / 4</span><h2 class="question" style="margin-top:14px">${q[1]}</h2><p class="helper">正確でなくても、近いものを選べば大丈夫です。</p><div class="single-options">${q[2].map(x=>`<button class="${state.answers[q[0]]===x?'active':''}" data-answer="${q[0]}" data-value="${x}">${x}</button>`).join('')}</div><div class="navrow"><button class="btn" data-action="q-back">戻る</button><button class="btn primary" data-action="q-next">${state.step===3?'診断する':'次へ'}</button></div></div>`;
 $('#thinking').innerHTML=`<div class="card thinking"><h2>回答をもとに考えています</h2><p class="helper">できるだけ小さく、現実的に始められる方法を整理しています。</p><div class="dots"><span></span><span></span><span></span></div></div>`;
 const p=pain(),s=service();
 $('#result').innerHTML=`<div class="card result-hero"><span class="label">診断結果</span><h2>一番もったいないのは<br>「${p?.[1]||'日々の手作業'}」です。</h2><p>全部を変える必要はありません。まず、この作業だけ小さく改善するのが現実的です。</p></div><div class="grid c3" style="margin-top:13px"><div class="card kpi"><span>現在使っている時間</span><strong>月約${hours()}時間</strong><small>回答からの概算</small></div><div class="card kpi"><span>減らせる可能性</span><strong>月約${saved()}時間</strong><small>無理のない削減目安</small></div><div class="card kpi"><span>年間の改善余地</span><strong>${annual()}時間</strong><small>約${Math.round(annual()/8)}日分</small></div></div><div class="grid c2" style="margin-top:13px"><div class="card panel recommend"><span class="tag green">あなたへのおすすめ</span><h3 style="margin-top:10px">${s[0]}</h3><p>${s[2]}</p><div class="price">${Math.round(s[1]/10000)}万円〜</div><p>最初から大きく導入せず、1つの作業で効果を確認してから広げます。</p></div><div class="card panel note"><h3>なぜこれが最初なのか</h3><p>この作業は「${state.answers.amount}」発生し、1回あたり「${state.answers.time}」かかっています。さらに「${state.answers.repeat}」ため、仕組み化しやすい可能性があります。</p><span class="tag amber">難しいシステムは不要</span></div></div><div class="navrow"><button class="btn" data-go="pain">選び直す</button><button class="btn primary" data-go="future">次へ</button></div>`;
 $('#future').innerHTML=`<div class="card panel center-card"><span class="tag green">年間約${annual()}時間</span><h2 class="question" style="margin-top:14px">その時間が戻ってきたら、何に使いたいですか？</h2><p class="helper">改善後の目的を選ぶと、提案内容がより分かりやすくなります。</p><div class="future-grid">${['営業','現場','休み','家族','趣味'].map(x=>`<button class="future ${state.future===x?'active':''}" data-future="${x}">${x}</button>`).join('')}</div><div class="navrow"><button class="btn" data-go="result">戻る</button><button class="btn primary ${state.future?'':'disabled'}" data-action="future-next">次へ</button></div></div>`;
 const c=state.contact,link=(label,url,kind='')=>url?`<a class="btn ${kind}" href="${esc(url)}" target="_blank" rel="noopener" style="text-decoration:none">${label}</a>`:`<button class="btn ${kind} disabled">${label}<br><small>準備中</small></button>`;
 $('#contact').innerHTML=`<div class="card cta center-card"><span class="tag blue">結果を見るだけでも大丈夫です</span><h3 style="margin-top:14px">この作業、本当に減らせるか確認しませんか？</h3><p>実際に使っている書類や画面を一つ見ながら、無理なく始められる方法を整理します。強引な営業は行いません。</p><div class="cta-buttons">${link('無料相談を申し込む',c.form,'primary')}${link('LINEで相談する',c.line,'green')}${link('ホームページを見る',c.website)}</div><p style="margin-top:18px"><b>${esc(c.business)}</b><br>${esc(c.area)}</p>${state.mode==='face'?'<button class="btn text" data-go="sales">営業担当メモを見る</button>':''}</div>`;
 const script=`【入り方】\n今日はAIやシステムを売る話ではなく、普段面倒に感じている仕事を一つ減らせないか確認します。\n\n【確認できた課題】\n一番負担なのは「${p?.[1]||'未選択'}」です。現在は月約${hours()}時間使っている可能性があります。\n\n【提案】\n最初におすすめするのは「${s[0]}」です。全部を変えず、この業務だけで月約${saved()}時間減らせるか試します。\n\n【未来】\n空いた時間は「${state.future||'未確認'}」に使いたいとのことです。`;
 $('#sales').innerHTML=`<div class="grid c2"><div class="card panel admin"><h3>営業担当メモ</h3><div class="admin-grid"><div class="field"><label>決裁者</label><select data-sales="decision">${['不明','本人・代表者','他の決裁者あり'].map(x=>`<option ${state.sales.decision===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>予算感</label><select data-sales="budget">${['未確認','5万円未満','5〜10万円','10〜30万円','30万円以上'].map(x=>`<option ${state.sales.budget===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>温度感</label><select data-sales="temperature">${['低','中','高'].map(x=>`<option ${state.sales.temperature===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field" style="grid-column:1/-1"><label>面談メモ</label><textarea data-sales="memo">${esc(state.sales.memo)}</textarea></div></div></div><div class="card panel"><div class="head"><h3>やさしい提案トーク</h3><button class="btn" data-action="copy">コピー</button></div><div class="script" id="scriptText">${esc(script)}</div></div></div><div class="navrow"><button class="btn" data-go="contact">顧客画面へ</button><button class="btn primary" data-go="report">診断書を見る</button></div>`;
 $('#settings').innerHTML=`<div class="card panel admin"><h3>連絡先・リンク設定</h3><p class="sub">未定の項目は空欄で構いません。</p><div class="admin-grid">${[['business','屋号・会社名'],['person','担当者名'],['website','ホームページURL'],['line','LINE URL'],['email','メールアドレス'],['phone','電話番号'],['form','無料相談フォームURL'],['area','対応地域']].map(x=>`<div class="field"><label>${x[1]}</label><input data-contact="${x[0]}" value="${esc(c[x[0]])}"></div>`).join('')}</div><div class="navrow"><button class="btn primary" data-action="save-settings">設定を保存</button></div></div>`;
 $('#report').innerHTML=`<div class="report"><div class="cover"><span>仕事ラクラク診断</span><h2>「面倒な仕事」を減らす改善案</h2><p>${new Date().toLocaleDateString('ja-JP')}｜${esc(c.business)}</p></div><div class="rsec"><h3>1．一番負担になっている仕事</h3><p>${p?.[1]||'未選択'}：${p?.[2]||''}</p></div><div class="rsec"><h3>2．時間の改善余地</h3><table><tr><th>現在</th><th>削減の可能性</th><th>年間</th></tr><tr><td>月約${hours()}時間</td><td>月約${saved()}時間</td><td>約${annual()}時間</td></tr></table></div><div class="rsec"><h3>3．最初におすすめする改善</h3><h3>${s[0]}</h3><p>${s[2]}</p><div class="price">${Math.round(s[1]/10000)}万円〜</div></div><div class="rsec"><h3>4．改善後に増やしたい時間</h3><p>${state.future||'未選択'}に使う時間を増やすことを目指します。</p></div><div class="rsec"><h3>お問い合わせ</h3><p><b>${esc(c.business)}</b><br>${esc(c.person)}<br>${esc(c.email)}<br>${esc(c.phone)}<br>${esc(c.website)}<br>${esc(c.area)}</p></div><button class="btn primary no-print" data-action="print">PDF保存・印刷</button></div>`;
 const progress=!state.pain?0:state.step<4?20+state.step*15:100;$('#progressBar').style.width=progress+'%';$('#progressText').textContent=progress+'%';$('#netMode').classList.toggle('active',state.mode==='net');$('#faceMode').classList.toggle('active',state.mode==='face');$$('.face-only').forEach(x=>x.style.display=state.mode==='face'?'block':'none');bind();show(state.screen==='thinking'?'welcome':state.screen)
}
function bind(){
 $$('[data-go]').forEach(x=>x.onclick=()=>show(x.dataset.go));$$('[data-view]').forEach(x=>x.onclick=()=>show(x.dataset.view));
 $$('[data-pain]').forEach(x=>x.onclick=()=>{state.pain=x.dataset.pain;state.step=0;state.screen='pain';save();render()});
 $$('[data-answer]').forEach(x=>x.onclick=()=>{state.answers[x.dataset.answer]=x.dataset.value;save();render()});
 $$('[data-future]').forEach(x=>x.onclick=()=>{state.future=x.dataset.future;save();render()});
 $$('[data-sales]').forEach(x=>x.onchange=()=>{state.sales[x.dataset.sales]=x.value;save()});
 $$('[data-contact]').forEach(x=>x.oninput=()=>state.contact[x.dataset.contact]=x.value);
 $$('[data-action]').forEach(x=>x.onclick=async()=>{const a=x.dataset.action;if(a==='start')show('pain');if(a==='pain-next'){if(!state.pain)return toast('1つ選んでください');state.step=0;save();render();show('question')}if(a==='q-back'){if(state.step===0)show('pain');else{state.step--;save();render();show('question')}}if(a==='q-next'){if(state.step<3){state.step++;save();render();show('question')}else{state.step=4;save();render();show('thinking');setTimeout(()=>{state.screen='result';save();render()},1200)}}if(a==='future-next'){if(!state.future)return toast('1つ選んでください');show('contact')}if(a==='copy'){try{await navigator.clipboard.writeText($('#scriptText').textContent);toast('コピーしました')}catch{toast('コピーできませんでした')}}if(a==='save-settings'){save();render();show('settings');toast('設定を保存しました')}if(a==='print')window.print()});
}
$('#netMode').onclick=()=>{state.mode='net';state.screen='welcome';save();render()};$('#faceMode').onclick=()=>{state.mode='face';state.screen='welcome';save();render()};$('#restartBtn').onclick=()=>{if(confirm('診断内容を最初からやり直しますか？')){const mode=state.mode,contact=copy(state.contact);state=copy(DEFAULT);state.mode=mode;state.contact=contact;save();render();toast('診断内容をリセットしました')}};
render();